// mypo-client/src/app/shared/components/footer.component.ts
import { Component, signal } from '@angular/core';
import { RouterLink, Router, NavigationEnd } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [RouterLink],
  template: `
    @if (showFooter()) {
      <footer class="site-footer">
        <div class="footer-inner">
          <a routerLink="/" aria-label="MyPO home">
            <img src="assets/mypo-logo.png" alt="MyPO" class="f-logo-img" />
          </a>
          <div class="f-links">
            <a routerLink="/about">About</a>
            <a routerLink="/privacy">Privacy Policy</a>
            <a routerLink="/terms">Terms of Service</a>
            <a routerLink="/contact">Contact Us</a>
          </div>
          <p class="f-copy">© {{ year }} MyPO. All rights reserved.</p>
        </div>
      </footer>
    }
  `,
  styles: [`
    .site-footer {
      background: var(--navy, #111e33);
      padding: 1.25rem 1.5rem;
      margin-top: auto;
    }
    .footer-inner {
      max-width: 1200px; margin: 0 auto;
      display: flex; align-items: center;
      justify-content: space-between; flex-wrap: wrap; gap: 1.5rem;
    }
    .f-logo-img { height: 160px; width: auto; filter: brightness(0) invert(1); }
    .f-links { display: flex; gap: 1.5rem; flex-wrap: wrap; }
    .f-links a {
      color: rgba(255,255,255,.6); text-decoration: none;
      font-size: .9rem; font-weight: 500; transition: color .2s;
    }
    .f-links a:hover { color: #fff; }
    .f-copy { color: rgba(255,255,255,.4); font-size: .85rem; }
    @media (max-width: 640px) {
      .footer-inner { flex-direction: column; align-items: flex-start; }
    }
  `]
})
export class FooterComponent {
  showFooter = signal(false);
  year = new Date().getFullYear();

  /* hide only on auth pages — global footer shows everywhere else */
  private hidden = ['/auth', '/forgot-password', '/reset-password'];

  constructor(private router: Router) {
    const check = (url: string) => !this.hidden.includes(url.split('?')[0]);
    this.router.events.pipe(filter(e => e instanceof NavigationEnd)).subscribe((e: any) => {
      this.showFooter.set(check(e.urlAfterRedirects));
    });
    this.showFooter.set(check(this.router.url));
  }
}

// pofund-2f49e8fb-main/src/components/Footer.tsx
import { Link } from "react-router-dom";
import logo from "@/assets/mypo-logo.png";

const Footer = () => {
  return (
    <footer className="bg-primary py-12">
      <div className="container mx-auto px-4">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <Link to="/" className="flex items-center" aria-label="MyPO home">
            <img src={logo} alt="MyPO logo" loading="lazy" className="h-44 w-auto brightness-0 invert" width={256} height={256} />
          </Link>

          <div className="flex flex-wrap items-center justify-center gap-6 text-primary-foreground/70">
            <Link to="/about" className="hover:text-primary-foreground transition-colors">
              About
            </Link>
            <Link to="/privacy" className="hover:text-primary-foreground transition-colors">
              Privacy Policy
            </Link>
            <Link to="/terms" className="hover:text-primary-foreground transition-colors">
              Terms of Service
            </Link>
            <Link to="/contact" className="hover:text-primary-foreground transition-colors">
              Contact Us
            </Link>
          </div>

          <p className="text-primary-foreground/50 text-sm">
            © {new Date().getFullYear()} MyPO. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
